#!/bin/bash

# This file is for preparing all the needed environment variables on the host.

DOCKER_REPO_NAME="localhost:8081/docker"
DOCKER_IMAGE_NAME="postgres"
DOCKER_IMAGE_TAG="latest"
CONTAINER_NAME="postgresql"
CONTAINER_PORT="5432:5432"
POSTGRES_DB_NAME="postgredb"
POSTGRES_DB_USER="postgreuser"
POSTGRES_DB_PASSWORD="moning"
POSTGRES_APP_DATA_VOLUME="/backup/data/postgresql:/var/lib/postgresql/data"

# DOCKER_REPO_NAME
if [[ -z "${BAMBOO_DOCKER_REPO_NAME}" ]]
then
    echo "BAMBOO_DOCKER_REPO_NAME is empty"
    export DOCKER_REPO_NAME=$DOCKER_REPO_NAME
else
    export DOCKER_REPO_NAME=${BAMBOO_DOCKER_REPO_NAME}
fi
echo "DOCKER_REPO_NAME = $DOCKER_REPO_NAME"

# DOCKER_IMAGE_NAME
if [[ -z "${BAMBOO_DOCKER_IMAGE_NAME}" ]]
then
    echo "BAMBOO_DOCKER_IMAGE_NAME is empty"
    export DOCKER_IMAGE_NAME=$DOCKER_IMAGE_NAME
else
    export DOCKER_IMAGE_NAME=${BAMBOO_DOCKER_IMAGE_NAME}
fi
echo "DOCKER_IMAGE_NAME = $DOCKER_IMAGE_NAME"

# DOCKER_IMAGE_TAG
if [[ -z "${BAMBOO_DOCKER_IMAGE_TAG}" ]]
then
    echo "BAMBOO_DOCKER_IMAGE_TAG is empty"
    export DOCKER_IMAGE_TAG=$DOCKER_IMAGE_TAG
else
    export DOCKER_IMAGE_TAG=${BAMBOO_DOCKER_IMAGE_TAG}
fi
echo "DOCKER_IMAGE_TAG = $DOCKER_IMAGE_TAG"

# CONTAINER_NAME
if [[ -z "${BAMBOO_CONTAINER_NAME}" ]]
then
    echo "BAMBOO_CONTAINER_NAME is empty"
    export CONTAINER_NAME=$CONTAINER_NAME
else
    export CONTAINER_NAME=${BAMBOO_CONTAINER_NAME}
fi
echo "CONTAINER_NAME = $CONTAINER_NAME"

# CONTAINER_PORT
if [[ -z "${BAMBOO_CONTAINER_PORT}" ]]
then
    echo "BAMBOO_CONTAINER_PORT is empty"
    export CONTAINER_PORT=$CONTAINER_PORT
else
    export CONTAINER_PORT=${BAMBOO_CONTAINER_PORT}
fi
echo "CONTAINER_PORT = $CONTAINER_PORT"

# POSTGRES_DB_NAME
if [[ -z "${BAMBOO_POSTGRES_DB_NAME}" ]]
then
    echo "BAMBOO_POSTGRES_DB_NAME is empty"
    export POSTGRES_DB_NAME=$POSTGRES_DB_NAME
else
    export POSTGRES_DB_NAME=${BAMBOO_POSTGRES_DB_NAME}
fi
echo "POSTGRES_DB_NAME = $POSTGRES_DB_NAME"

# POSTGRES_DB_USER
if [[ -z "${BAMBOO_POSTGRES_DB_USER}" ]]
then
    echo "BAMBOO_POSTGRES_DB_USER is empty"
    export POSTGRES_DB_USER=$POSTGRES_DB_USER
else
    export POSTGRES_DB_USER=${BAMBOO_POSTGRES_DB_USER}
fi
echo "POSTGRES_DB_USER = $POSTGRES_DB_USER"

# POSTGRES_DB_PASSWORD
if [[ -z "${BAMBOO_POSTGRES_DB_PASSWORD}" ]]
then
    echo "BAMBOO_POSTGRES_DB_PASSWORD is empty"
    export POSTGRES_DB_PASSWORD=$POSTGRES_DB_PASSWORD
else
    export POSTGRES_DB_PASSWORD=${BAMBOO_POSTGRES_DB_PASSWORD}
fi
echo "POSTGRES_DB_PASSWORD = $POSTGRES_DB_PASSWORD"

# POSTGRES_APP_DATA_VOLUME
if [[ -z "${BAMBOO_POSTGRES_APP_DATA_VOLUME}" ]]
then
    echo "BAMBOO_POSTGRES_APP_DATA_VOLUME is empty"
    export POSTGRES_APP_DATA_VOLUME=$POSTGRES_APP_DATA_VOLUME
else
    export POSTGRES_APP_DATA_VOLUME=${BAMBOO_POSTGRES_APP_DATA_VOLUME}
fi
echo "POSTGRES_APP_DATA_VOLUME = $POSTGRES_APP_DATA_VOLUME"
